### ISSUE TITLE
[Feature] Please, add Folia support

### ISSUE THREAD

**Issue by roggy666** [GeyserMC/Hurricane#18]

**Comment by xcomcadx** [comment]
this already works on folia by adding the flag to plugin.yml

**Comment by MrRagtime** [comment]
> this already works on folia by adding the flag to plugin.yml

could you explain better what you mean ?

**Comment by Wandraker** [comment]
PluginInitializerManager] Initializing plugins...
[08:12:01] [Paper Plugin Remapper Thread - 2/INFO]: [PluginRemapper] Remapping plugin 'plugins/Hurricane.jar'...
[08:12:01] [ServerMain/ERROR]: [PluginRemapper] Encountered exception remapping plugins
java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to remap plugin jar 'plugins/Hurricane.jar'
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.RuntimeException: Failed to remap plugin jar 'plugins/Hurricane.jar'
	at io.papermc.paper.pluginremap.PluginRemapper.lambda$remap$7(PluginRemapper.java:362) ~[foldenor-1.21.8.jar:1.21.8-DEV-f1de313]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	... 4 more
Caused by: java.lang.RuntimeException: Failed to execute task org/geysermc/hurricane/relocations/configurate/ScopedConfigurationNode
	at net.neoforged.art.internal.AsyncHelper.invokeAll(AsyncHelper.java:56) ~[AutoRenamingTool-2.0.3.jar:?]
	at net.neoforged.art.internal.AsyncHelper.consumeAll(AsyncHelper.java:36) ~[AutoRenamingTool-2.0.3.jar:?]
	at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:161) ~[foldenor-1.21.8.jar:?]
	at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:79) ~[foldenor-1.21.8.jar:?]
	at io.papermc.paper.pluginremap.PluginRemapper.lambda$remap$7(PluginRemapper.java:359) ~[foldenor-1.21.8.jar:1.21.8-DEV-f1de313]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	... 4 more
Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 0
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at net.neoforged.art.internal.AsyncHelper.invokeAll(AsyncHelper.java:52) ~[AutoRenamingTool-2.0.3.jar:?]
	at net.neoforged.art.internal.AsyncHelper.consumeAll(AsyncHelper.java:36) ~[AutoRenamingTool-2.0.3.jar:?]
	at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:161) ~[foldenor-1.21.8.jar:?]
	at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:79) ~[foldenor-1.21.8.jar:?]
	at io.papermc.paper.pluginremap.PluginRemapper.lambda$remap$7(PluginRemapper.java:359) ~[foldenor-1.21.8.jar:1.21.8-DEV-f1de313]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	... 4 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 0
	at org.objectweb.asm.ClassReader.readShort(ClassReader.java:3635) ~[asm-9.8.jar:9.8]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:198) ~[asm-9.8.jar:9.8]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180) ~[asm-9.8.jar:9.8]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166) ~[asm-9.8.jar:9.8]
	at net.neoforged.art.internal.ClassProviderImpl$ClassInfo.<init>(ClassProviderImpl.java:104) ~[AutoRenamingTool-2.0.3.jar:?]
	at net.neoforged.art.internal.ClassProviderBuilderImpl.lambda$addClass$1(ClassProviderBuilderImpl.java:64) ~[AutoRenamingTool-2.0.3.jar:?]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at net.neoforged.art.internal.ClassProviderBuilderImpl.addClass(ClassProviderBuilderImpl.java:64) ~[AutoRenamingTool-2.0.3.jar:?]
	at net.neoforged.art.internal.RenamerImpl.lambda$run$2(RenamerImpl.java:162) ~[foldenor-1.21.8.jar:?]
	at net.neoforged.art.internal.AsyncHelper.lambda$null$0(AsyncHelper.java:33) ~[AutoRenamingTool-2.0.3.jar:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	... 3 more

**Comment by Wandraker** [comment]
Well.. Is it really supported? (p.s. I also checked on regular folia)

**Comment by Wandraker** [comment]
Does not work with addition ( folia-supported: true )
